### ISSUE TITLE
Random `FileNotFoundError` when repeatedly calling `np.save` with the same jupyterlite site is opened in 2 concurrent browser tabs

### ISSUE THREAD

**Issue by ogrisel** [jupyterlite/jupyterlite#1582]
The following code seems to crash because of a bad interaction with the jupyterlite synchronized filesystem.

Steps to reproduce:

- open https://jupyter.org/try-jupyter/lab/
- open https://jupyter.org/try-jupyter/lab/ again in a different browser tabs while keeping the previous tab open;
- create a pyodide notebooks with the following cell in one of the 2 jupyterlite instance:

```python
import numpy as np
from pathlib import Path

folder = Path("generated_data")
folder.mkdir(exist_ok=True)

for i in range(1000):
    data = np.random.randn(int(1e1))
    np.save(folder / f"data_{i}.npy", data)
    if i % 10 == 0:
        print(i)
```

- run it and get:

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 9
      7 for i in range(1000):
      8     data = np.random.randn(int(1e1))
----> 9     np.save(folder / f"data_{i}.npy", data)

File /lib/python3.12/site-packages/numpy/lib/_npyio_impl.py:570, in save(file, arr, allow_pickle, fix_imports)
    568     if not file.endswith('.npy'):
    569         file = file + '.npy'
--> 570     file_ctx = open(file, "wb")
    572 with file_ctx as fid:
    573     arr = np.asanyarray(arr)

FileNotFoundError: [Errno 44] No such file or directory: 'generated_data/data_455.npy' 
```

The precise loop iteration index that triggers the failure is random.

The JS console displays:

<details>

```
Loading numpy [pyodide.asm.js:10:94840](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
Loaded numpy [pyodide.asm.js:10:94840](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
XHRGET
https://probabl-ai.github.io/calibration-cost-sensitive-learning/jupyterlite/api/contents/generated_data/all.json
[HTTP/2 404  138ms]

don't worry, about SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data... nothing's broken. If there had been a
          file at https://probabl-ai.github.io/calibration-cost-sensitive-learning/jupyterlite/api/contents/generated_data/all.json, you might see some more files. [contents.js:724:24](webpack://_JUPYTERLAB.CORE_OUTPUT/packages/contents/lib/contents.js)
XHRGET
https://probabl-ai.github.io/calibration-cost-sensitive-learning/jupyterlite/api/contents/lib/python3.12/site-packages/numpy/lib/all.json
[HTTP/2 404  138ms]

don't worry, about SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data... nothing's broken. If there had been a
          file at https://probabl-ai.github.io/calibration-cost-sensitive-learning/jupyterlite/api/contents/lib/python3.12/site-packages/numpy/lib/all.json, you might see some more files. [contents.js:724:24](webpack://_JUPYTERLAB.CORE_OUTPUT/packages/contents/lib/contents.js)

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data [serverconnection.js:90:24](webpack://_JUPYTERLAB.CORE_OUTPUT/node_modules/@jupyterlab/services/lib/serverconnection.js)

Could not resolve location of /lib/python3.12/site-packages/numpy/lib/_npyio_impl.py on server [registry.js:317:28](webpack://_JUPYTERLAB.CORE_OUTPUT/node_modules/@jupyterlab/rendermime/lib/registry.js)
Path resolution bailing: does not exist [renderers.js:923:24](webpack://_JUPYTERLAB.CORE_OUTPUT/node_modules/@jupyterlab/rendermime/lib/renderers.js)

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data [serverconnection.js:90:24](webpack://_JUPYTERLAB.CORE_OUTPUT/node_modules/@jupyterlab/services/lib/serverconnection.js)

Could not resolve location of /data_105.npy on server [registry.js:317:28](webpack://_JUPYTERLAB.CORE_OUTPUT/node_modules/@jupyterlab/rendermime/lib/registry.js)
Path resolution bailing: does not exist [renderers.js:923:24](webpack://_JUPYTERLAB.CORE_OUTPUT/node_modules/@jupyterlab/rendermime/lib/renderers.js)

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data [serverconnection.js:90:24](webpack://_JUPYTERLAB.CORE_OUTPUT/node_modules/@jupyterlab/services/lib/serverconnection.js)
```

</details>

other times I got a different error in the JS console:

<details>

```
Loading numpy [pyodide.asm.js:10:94840](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
Loaded numpy [pyodide.asm.js:10:94840](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
don't worry, about SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data... nothing's broken. If there had been a
          file at https://probabl-ai.github.io/calibration-cost-sensitive-learning/jupyterlite/api/contents/generated_data/all.json, you might see some more files. 5 [contents.js:724:24](webpack://_JUPYTERLAB.CORE_OUTPUT/packages/contents/lib/contents.js)

Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers. [pyodide.asm.js:10:48512](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)

The cause of the fatal error was: [pyodide.asm.js:10:48612](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)

Stack (most recent call first): [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/numpy/lib/_npyio_impl.py", line 570 in save [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "<ipython-input-1-e91e2d520b89>", line 9 in <module> [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577 in run_code [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517 in run_ast_nodes [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334 in run_cell_async [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 129 in _pseudo_sync_runner [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130 in _run_cell [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075 in run_cell [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/pyodide_kernel/kernel.py", line 103 in run [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python312.zip/asyncio/events.py", line 88 in _run [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)
  File "/lib/python312.zip/pyodide/webloop.py", line 332 in run_handle [pyodide.asm.js:10:98723](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)

Recursive call to fatal_error. Inner error was: 3 [pyodide.asm.js:10:48299](https://cdn.jsdelivr.net/pyodide/v0.27.1/full/pyodide.asm.js)

TypeError: stat.atime is undefined
```

</details>

I got the error on this deployment:

https://jupyter.org/try-jupyter/lab/

but I can also reproduce on:

https://jupyterlite-pyodide-kernel.readthedocs.io/en/latest/_static/lab/index.html

I check the running pyodide version by executing the following code cell:

```python
import pyodide
pyodide.__version__
```

The problem happens with Firefox, Chrome, Safari (macOS) with either:
- jupyterlite 0.5.1 and pyodide 0.27.1
- jupyterlite 0.5.1 and pyodide 0.27.2

Important note: it appears that it goes away when running this in a private browsing window on Firefox. It also goes away (although there are noisy warnings in the JS console) if the browser has only one tab with the jupyterlite site open.

This shares some error messages with #1576 but #1576 can be triggered with a single browser tab as far as I understand.

**Comment by ogrisel** [comment]
The same snippet can also crash with chrome:

<details>

```
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:10
callPyObjectKwargsPromising @ pyodide.asm.js:10
await in callPyObjectKwargsPromising
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
Zn.e.port1.onmessage @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:10
callPyObjectKwargsPromising @ pyodide.asm.js:10
await in callPyObjectKwargsPromising
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
Zn.e.port1.onmessage @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 TypeError: t.push is not a function
    at fe.readdir (comlink.worker.js:4:3998)
    at We.readdir (comlink.worker.js:4:3270)
    at Object.readdir (pyodide.asm.js:10:219371)
    at ___syscall_getdents64 (pyodide.asm.js:10:264426)
    at pyodide.asm.wasm:0x4a962d
    at pyodide.asm.wasm:0x3df737
    at pyodide.asm.wasm:0x2a1730
    at pyodide.asm.wasm:0x29846b
    at pyodide.asm.wasm:0x29605f
    at pyodide.asm.wasm:0x20c217
API.fatal_error @ pyodide.asm.js:10
callPyObjectKwargsPromising @ pyodide.asm.js:10
await in callPyObjectKwargsPromising
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
Zn.e.port1.onmessage @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 Stack (most recent call first):
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1648 in _fill_cache
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1605 in find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1502 in _get_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1528 in find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1262 in _find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1322 in _find_and_load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1387 in _gcd_import
pyodide.asm.js:10   File "/lib/python312.zip/importlib/__init__.py", line 90 in import_module
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/extensions.py", line 77 in _load_extension
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/extensions.py", line 62 in load_extension
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/shellapp.py", line 282 in init_extensions
pyodide.asm.js:10   File "/lib/python3.12/site-packages/pyodide_kernel/interpreter.py", line 72 in initialize
pyodide.asm.js:10   File "/lib/python3.12/site-packages/pyodide_kernel/__init__.py", line 27 in <module>
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 995 in exec_module
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
pyodide.asm.js:10   File "<exec>", line 7 in <module>
pyodide.asm.js:10   File "/lib/python312.zip/_pyodide/_base.py", line 413 in run_async
pyodide.asm.js:10   File "/lib/python312.zip/_pyodide/_base.py", line 597 in eval_code_async
pyodide.asm.js:10   File "/lib/python312.zip/asyncio/events.py", line 88 in _run
pyodide.asm.js:10   File "/lib/python312.zip/pyodide/webloop.py", line 332 in run_handle
pyodide.asm.js:10 Uncaught (in promise) TypeError: t.push is not a function
    at fe.readdir (comlink.worker.js:4:3998)
    at We.readdir (comlink.worker.js:4:3270)
    at Object.readdir (pyodide.asm.js:10:219371)
    at ___syscall_getdents64 (pyodide.asm.js:10:264426)
    at pyodide.asm.wasm:0x4a962d
    at pyodide.asm.wasm:0x3df737
    at pyodide.asm.wasm:0x2a1730
    at pyodide.asm.wasm:0x29846b
    at pyodide.asm.wasm:0x29605f
    at pyodide.asm.wasm:0x20c217
```

</details>

**Comment by jtpio** [comment]
Thanks @ogrisel for the report 👍 

> it appears that it goes away when running this in a private browsing window on Firefox.

Yeah this seems to indicate it is likely related with the Service Worker and how the content is made visible to the kernel.

**Comment by jtpio** [comment]
We looked into this with @lesteve today.

And after debugging this a bit, it seems related to the use of the `BroadcastChannel` for the communication with the Service Worker.

The `BroadcastChannel` is defined here:

https://github.com/jupyterlite/jupyterlite/blob/f175a5d131b78a71103cf7e33947f03698df0755/packages/server/src/service-worker.ts#L9-L12

And the other one here: https://github.com/jupyterlite/jupyterlite/blob/f175a5d131b78a71103cf7e33947f03698df0755/packages/contents/src/broadcast.ts#L31

And it's only used here in the Service Worker:

https://github.com/jupyterlite/jupyterlite/blob/f175a5d131b78a71103cf7e33947f03698df0755/packages/server/src/service-worker.ts#L137-L149

But the problem with `BroadcastChannel` is that other tabs will get the file system requests as well, since they broadcast across tabs. When debugging this and setting a breakpoint in the second tab to block the execution, it seems to be fixing the issue.

I'm not sure why a `BroadcastChannel` was used in the first place for the communication, and not a more specific `MessageChannel` instead (1 to 1 communication). Maybe because it was more convenient to work with in the beginning.

So my guess is that we should switch to using a `MessageChannel` instead, to avoid "leaking" requests across tabs. `BroadcastChannel` are useful for other use cases such as syncing information across tabs, but not for file system access in its current implementation.

**Comment by jtpio** [comment]
> So my guess is that we should switch to using a `MessageChannel` instead, to avoid "leaking" requests across tabs. `BroadcastChannel` are useful for other use cases such as syncing information across tabs, but not for file system access in its current implementation.

This may lead to some breaking changes for kernels, so I'll try to have a look in the coming days so we can have that fix for the upcoming `0.6.0` release.

**Comment by jtpio** [comment]
In the meantime @ogrisel, maybe you would like to try serving a JupyterLite site with the COOP / COEP headers: https://jupyterlite.readthedocs.io/en/stable/howto/content/python.html#synchronous-communication-with-the-kernel-over-atomics-wait-via-sharedarraybuffer

They enable the use of the `SharedArrayBuffer` to allow accessing the file system, as an alternative to the Service Worker approach.

If you have Node installed, you can start a server with these headers with: `npx static-handler --cors --coop --coep --corp ./`

When I tried that approach locally I was able to run the code above several times with multiple tabs opened, without triggering the issue.

**Comment by ogrisel** [comment]
Unfortunately github pages do not support setting those headers: https://github.com/orgs/community/discussions/13309

But it should be possible with netlify.

**Comment by lesteve** [comment]
Yeah this is a known GH-pages limitation, Vercel also allows it which is why jupyterlite-terminal is on Vercel: https://jupyterlite-terminal.vercel.app/ (I don't remember why but jupyterlite-terminal needs `SharedArrayBuffer`.

**Comment by jtpio** [comment]
@ogrisel @lesteve would you be able to try the changes from https://github.com/jupyterlite/jupyterlite/pull/1608 using the ReadTheDocs preview, in a browser supporting `ServiceWorker` (not Firefox in private window)? https://jupyterlite--1608.org.readthedocs.build/en/1608/_static/lab/index.html

**Comment by ogrisel** [comment]
@jtpio I tried to execute my reproducer in https://jupyterlite--1608.org.readthedocs.build/en/1608/_static/lab/index.html on a regular firefox (the first time with 2 browser tabs open and the second time with a single tab open) and I got the following crash in the JS console (and not output in the jupyterlite UI):

```
Loaded Pygments, asttokens, decorator, executing, ipython, matplotlib-inline, prompt_toolkit, pure-eval, six, stack-data, wcwidth [pyodide.asm.js:10:95004](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)

Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time [327.68dbf8491690b3aff1e7.js:1:5783](https://jupyterlite--1608.org.readthedocs.build/en/1608/_static/extensions/@jupyter-widgets/jupyterlab-manager/static/327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7)

Failed to load ‘https://jupyterlite--1608.org.readthedocs.build/en/1608/_static/api/drive’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: messagePort is undefined’. [service-worker.js:1:1411](https://jupyterlite--1608.org.readthedocs.build/en/1608/_static/service-worker.js?enableCache=false)
NetworkError: A network error occurred. [352.3c4544f2a442d160f6ac.js:2:208749](https://jupyterlite--1608.org.readthedocs.build/en/1608/_static/extensions/@jupyterlite/pyodide-kernel-extension/static/352.3c4544f2a442d160f6ac.js?v=3c4544f2a442d160f6ac)

Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers. [pyodide.asm.js:10:48670](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)

The cause of the fatal error was: [pyodide.asm.js:10:48770](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)

Stack (most recent call first): [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap_external>", line 147 in _path_stat [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen zipimport>", line 75 in __init__ [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap_external>", line 1463 in _path_hooks [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap_external>", line 1487 in _path_importer_cache [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap_external>", line 1500 in _get_spec [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap_external>", line 1528 in find_spec [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap>", line 1262 in _find_spec [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap>", line 1322 in _find_and_load_unlocked [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap>", line 1387 in _gcd_import [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python312.zip/importlib/__init__.py", line 90 in import_module [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/IPython/core/extensions.py", line 77 in _load_extension [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/IPython/core/extensions.py", line 62 in load_extension [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/IPython/core/shellapp.py", line 282 in init_extensions [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/pyodide_kernel/interpreter.py", line 72 in initialize [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python3.12/site-packages/pyodide_kernel/__init__.py", line 27 in <module> [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "<exec>", line 8 in <module> [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python312.zip/_pyodide/_base.py", line 413 in run_async [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python312.zip/_pyodide/_base.py", line 597 in eval_code_async [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python312.zip/asyncio/events.py", line 88 in _run [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
  File "/lib/python312.zip/pyodide/webloop.py", line 339 in run_handle [pyodide.asm.js:10:98922](https://cdn.jsdelivr.net/pyodide/v0.27.4/full/pyodide.asm.js)
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

**Comment by ogrisel** [comment]
Here is the JS console log when running the same cell on a single chrome tab:

```
Loaded Pygments, asttokens, decorator, executing, ipython, matplotlib-inline, prompt_toolkit, pure-eval, six, stack-data, wcwidth
The FetchEvent for "https://jupyterlite--1608.org.readthedocs.build/en/1608/_static/api/drive" resulted in a network error response: the promise was rejected.
Promise.then
onFetch @ service-worker.js?enableCache=false:1Understand this warningAI
service-worker.js?enableCache=false:1 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'onmessage')
    at service-worker.js?enableCache=false:1:1312
    at new Promise (<anonymous>)
    at broadcastOne (service-worker.js?enableCache=false:1:1274)
    at onFetch (service-worker.js?enableCache=false:1:560)
(anonymous) @ service-worker.js?enableCache=false:1
broadcastOne @ service-worker.js?enableCache=false:1
onFetch @ service-worker.js?enableCache=false:1Understand this errorAI
service-worker.js?enableCache=false:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'postMessage')
    at broadcastOne (service-worker.js?enableCache=false:1:1423)
broadcastOne @ service-worker.js?enableCache=false:1
await in broadcastOne
onFetch @ service-worker.js?enableCache=false:1Understand this errorAI
comlink.worker.js:10 NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://jupyterlite--1608.org.readthedocs.build/en/1608/_static/api/drive'.
    at ut.request (comlink.worker.js:10:5380)
    at ut.getattr (comlink.worker.js:10:4881)
    at Vn.getattr (comlink.worker.js:10:1943)
    at stat (pyodide.asm.js:10:221040)
    at Object.doStat (pyodide.asm.js:10:238341)
    at ___syscall_stat64 (pyodide.asm.js:10:280539)
    at pyodide.asm.wasm:0x49986c
    at pyodide.asm.wasm:0x4b34c7
    at pyodide.asm.wasm:0x3de63c
    at pyodide.asm.wasm:0x3ddced
request @ comlink.worker.js:10
getattr @ comlink.worker.js:10
getattr @ comlink.worker.js:10
stat @ pyodide.asm.js:10
doStat @ pyodide.asm.js:10
___syscall_stat64 @ pyodide.asm.js:10
$fstatat @ pyodide.asm.wasm:0x49986c
$stat @ pyodide.asm.wasm:0x4b34c7
$func6540 @ pyodide.asm.wasm:0x3de63c
$func6537 @ pyodide.asm.wasm:0x3ddced
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2a17f1
$func3429 @ pyodide.asm.wasm:0x2a72bf
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1c508f
$_PyObject_FastCallDictTstate @ pyodide.asm.wasm:0x1c45b9
$_PyObject_Call_Prepend @ pyodide.asm.wasm:0x1c52b0
$func2652 @ pyodide.asm.wasm:0x22aed4
$func2584 @ pyodide.asm.wasm:0x2252c9
$func4586 @ pyodide.asm.wasm:0x328642
$_PyObject_MakeTpCall @ pyodide.asm.wasm:0x1c44db
$PyObject_Vectorcall @ pyodide.asm.wasm:0x1c4ce6
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2a2a6d
$PyEval_EvalCode @ pyodide.asm.wasm:0x29852c
$func3393 @ pyodide.asm.wasm:0x296120
$func2184 @ pyodide.asm.wasm:0x20c2d8
$func1159 @ pyodide.asm.wasm:0x1c4bc2
$_PyObject_Call @ pyodide.asm.wasm:0x1c4ed1
$PyObject_Call @ pyodide.asm.wasm:0x1c4f4f
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2a0d61
$func3429 @ pyodide.asm.wasm:0x2a72bf
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1c508f
$func1180 @ pyodide.asm.wasm:0x1c5df9
$PyObject_CallMethodObjArgs @ pyodide.asm.wasm:0x1c5bd5
$PyImport_ImportModuleLevelObject @ pyodide.asm.wasm:0x2de713
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2a4dd7
$func1544 @ pyodide.asm.wasm:0x1daa06
$func1566 @ pyodide.asm.wasm:0x1db8a3
$PyIter_Send @ pyodide.asm.wasm:0x1b0750
$func5021 @ pyodide.asm.wasm:0x346f07
$func5019 @ pyodide.asm.wasm:0x346c4c
$func5027 @ pyodide.asm.wasm:0x3483f5
$func4586 @ pyodide.asm.wasm:0x328635
$func2186 @ pyodide.asm.wasm:0x20c577
$func3622 @ pyodide.asm.wasm:0x2ca3a1
$func2184 @ pyodide.asm.wasm:0x20c2d8
$func1159 @ pyodide.asm.wasm:0x1c4bc2
$_PyObject_Call @ pyodide.asm.wasm:0x1c4ed1
$PyObject_Call @ pyodide.asm.wasm:0x1c4f4f
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2a0d61
$func3429 @ pyodide.asm.wasm:0x2a72bf
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1c508f
$PyObject_Vectorcall @ pyodide.asm.wasm:0x1c4cf8
$_pyproxy_apply @ pyodide.asm.wasm:0x177bbf
$_pyproxy_apply_promising @ pyodide.asm.wasm:0x177ce1
wrapper @ pyodide.asm.js:10
promisingApply @ pyodide.asm.js:10
callPyObjectKwargsPromising @ pyodide.asm.js:10
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
e.port1.onmessage @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:10
callPyObjectKwargsPromising @ pyodide.asm.js:10
await in callPyObjectKwargsPromising
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
e.port1.onmessage @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:10
callPyObjectKwargsPromising @ pyodide.asm.js:10
await in callPyObjectKwargsPromising
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
e.port1.onmessage @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ut.request (comlink.worker.js:10:5513)
    at ut.getattr (comlink.worker.js:10:4881)
    at Vn.getattr (comlink.worker.js:10:1943)
    at stat (pyodide.asm.js:10:221040)
    at Object.doStat (pyodide.asm.js:10:238341)
    at ___syscall_stat64 (pyodide.asm.js:10:280539)
    at pyodide.asm.wasm:0x49986c
    at pyodide.asm.wasm:0x4b34c7
    at pyodide.asm.wasm:0x3de63c
API.fatal_error @ pyodide.asm.js:10
callPyObjectKwargsPromising @ pyodide.asm.js:10
await in callPyObjectKwargsPromising
Module.callPyObjectMaybePromising @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
e.port1.onmessage @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 Stack (most recent call first):
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 147 in _path_stat
pyodide.asm.js:10   File "<frozen zipimport>", line 75 in __init__
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1463 in _path_hooks
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1487 in _path_importer_cache
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1500 in _get_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1528 in find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1262 in _find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1322 in _find_and_load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1387 in _gcd_import
pyodide.asm.js:10   File "/lib/python312.zip/importlib/__init__.py", line 90 in import_module
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/extensions.py", line 77 in _load_extension
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/extensions.py", line 62 in load_extension
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/shellapp.py", line 282 in init_extensions
pyodide.asm.js:10   File "/lib/python3.12/site-packages/pyodide_kernel/interpreter.py", line 72 in initialize
pyodide.asm.js:10   File "/lib/python3.12/site-packages/pyodide_kernel/__init__.py", line 27 in <module>
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 995 in exec_module
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
pyodide.asm.js:10   File "<exec>", line 8 in <module>
pyodide.asm.js:10   File "/lib/python312.zip/_pyodide/_base.py", line 413 in run_async
pyodide.asm.js:10   File "/lib/python312.zip/_pyodide/_base.py", line 597 in eval_code_async
pyodide.asm.js:10   File "/lib/python312.zip/asyncio/events.py", line 88 in _run
pyodide.asm.js:10   File "/lib/python312.zip/pyodide/webloop.py", line 339 in run_handle
VM73:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ut.request (comlink.worker.js:10:5513)
    at ut.getattr (comlink.worker.js:10:4881)
    at Vn.getattr (comlink.worker.js:10:1943)
    at stat (pyodide.asm.js:10:221040)
    at Object.doStat (pyodide.asm.js:10:238341)
    at ___syscall_stat64 (pyodide.asm.js:10:280539)
    at pyodide.asm.wasm:0x49986c
    at pyodide.asm.wasm:0x4b34c7
    at pyodide.asm.wasm:0x3de63c
```

**Comment by ogrisel** [comment]
Running any Python code in the first cell will trigger the above errors, it's not related to the FS.

**Comment by jtpio** [comment]
OK thanks for testing. It looks like it was related to the message port not being available. I've pushed new changes to handle that, which should be available on RTD in a couple of minutes.

Also when testing this it may be worth going to the dev tools and unregistering previously registered service workers, or try in a new Chrome private windows.

**Comment by jtpio** [comment]
This is what it looks like when testing in a Chrome 134 private window with the latest changes from https://github.com/jupyterlite/jupyterlite/pull/1608, which now include the related change to `jupyterlite-pyodide-kernel`: https://jupyterlite--1608.org.readthedocs.build/en/1608/_static/lab/index.html

https://github.com/user-attachments/assets/1d58a080-e289-42bc-b975-f72ea3e31685

With the current `main` (without these changes), I am able to reproduce the issue easily otherwise.

**Comment by ogrisel** [comment]
I also tried in firefox unregistering service workers using the following snippet:

https://stackoverflow.com/a/41675764/163740

When running the code in of the reproducer concurrently in two open tabs, one of them seems to slow down to a crawl (I added some print statements to monitor the progress in the loop), but I no longer observe the original `FileNotFoundError` traceback in Python nor the errors in the JS console.

So the original issue seems to be fixed for me. Thank you very much @jtpio!

**Comment by jtpio** [comment]
Nice, thanks for testing!

> When running the code in of the reproducer concurrently in two open tabs, one of them seems to slow down to a crawl (I added some print statements to monitor the progress in the loop), but I no longer observe the original FileNotFoundError traceback in Python nor the errors in the JS console.

Just to confirm, you mean running the same code snippet above at the same time from the two browser tabs? I guess the slow down may be because they both try to write to the browser storage simultaneously, which would increase load on the local IndexedDB?

**Comment by jtpio** [comment]
FYI the released that shipped https://github.com/jupyterlite/jupyterlite/pull/1608 was yanked because https://github.com/jupyterlite/jupyterlite/pull/1608 was not fully functional.

But there should be a way to make it work based on the comments in https://github.com/jupyterlite/jupyterlite/pull/1608#pullrequestreview-2729621461.

We can release `0.6.0a8` once a fix is merged.

**Comment by jtpio** [comment]
Re-opening as this still needs some investigation.

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlite/jupyterlite/pull/1621 to look into another (hopefully a bit more robust) approach.

**Comment by jtpio** [comment]
FYI this should now be fixed with `jupyterlite-core==0.6.0a8` and `jupyterlite-pyodide-kernel==0.6.0a5`.

Feel free to comment here or re-open if you're still seeing the issue, thanks!

**Comment by lesteve** [comment]
I still reproduce the issue after unregistering the service worker 🤔.

I think you need to run the rhs JupyterLite cell while the loop on the lhs JupyterLite is still running. I guess to reproduce the issue both JupyterLite need to access the filesystem at somewhat the same time?

Just out of curiosity you don't see errors in the rhs console log, even without running anything? On Firefox I get `Uncaught (in promise) TypeError: e.data is null`. I seem to remember on Chromium the error may be a bit different.

**Comment by jtpio** [comment]
Ah, it does seems to be reproducible with a longer loop (and hence more file writes). The cell in the second tab gets stuck when executed while the cell in the first tab is still running:

![Image](https://github.com/user-attachments/assets/7a557fb6-f049-4691-ad01-7350609756d6)

But it looks like a different issue than the original one posted here? The original issue was about being able to write files from multiples tabs. And it seems #1621 helped get pass this first issue, and now we are facing a new one.

So let's track that separately?

**Comment by lesteve** [comment]
Great that you are able to reproduce (as someone that reports an issue and hopes that he is not the only one seeing it 😅).

You are right that the original issue was reproducible with executing code in only one of the 2 JupyterLite.

The new one is what happens when you try to interact with the filesystem in both JupyterLite at the same time, so indeed feel free to track it in a separate issue.

In practice, my guess is that this new bug is less likely to happen than the original bug but it's only a guess.

**Comment by jtpio** [comment]
Cool, thanks again @lesteve for finding and reporting these issues, and spending time helping to reproduce them!

Let's continue in https://github.com/jupyterlite/jupyterlite/issues/1626 then.

**Comment by ogrisel** [comment]
Thanks very much for fixing those bugs @jtpio!
