### ISSUE TITLE
GitLab example does not work properly 

### ISSUE THREAD

**Issue by kolibril13** [jupyterlite/jupyterlite#799]
The PR https://github.com/jupyterlite/jupyterlite/pull/203 added a nice code snippet to set up JupyterLite in GitLab.
I wanted to reproduce this with a minimal example: This [GitLab repo](https://gitlab.gwdg.de/crc1456/livedocs/jupyter-lite-compare_view-demo) produces this [JupyterLite page](https://crc1456.pages.gwdg.de/livedocs/jupyter-lite-compare_view-demo/lab/index.html) without problems.
The only problem: The example notebook `hello.ipynb` does not show up, the notebook explorer is empty.
@benabel do you have an idea where I have to copy the notebook? Copying it into the `content/` folder does not work.
I've run this `.gitlab-ci.yml` file:
```
image: python
pages:
  stage: deploy
  before_script:
    - python -m pip install jupyterlite
    - mkdir -p content/
    - cp hello.ipynb content/

  script:
    - jupyter lite build --contents content --output-dir public
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - main # the branch you want to publish
```

Also, thanks @benabel for the example at https://gitlab.com/benabel/jupyterlite-template , but unfortunately this gives currently the following error ([full log here](https://gitlab.gwdg.de/crc1456/livedocs/jupyter-lite-compare_view-demo/-/jobs/964545)) when I run it in the Gitlab CI:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/doit/action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/jupyterlite/addons/base.py", line 223, in merge_one_jupyterlite
    out_path.write_text(json.dumps(config, **JSON_FMT), **UTF8)
  File "/usr/local/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/usr/local/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/builds/crc1456/livedocs/jupyter-lite-compare_view-demo/public/github-demo/repl/jupyter-lite.json'
```

**Comment by benabel** [comment]
@kolibril13 I can't debug this right now, but I have thos repo where I use extensively jupyterlite on gitlab https://framagit.org/lyceum/jupyterlite/ notebooks are placed in the notebooks dir and you can see it live at HTTPS://jupyterlite.lyceum.fr.

**Comment by benabel** [comment]
I have fixed the jupyterlab repo to include the repl: https://benabel.gitlab.io/jupyterlite-template/repl/.

It seems that the `repl` directory needs on the same directory than `contents`.

**Comment by kolibril13** [comment]
Thanks for this effort, your [new script](https://gitlab.com/benabel/jupyterlite-template/-/blob/main/.gitlab-ci.yml) builds without errors.
Now I am trying to make a minimal example for the JupyterLite documentation for it.
The build is running correctly, however the notebook still does not appear.
@benabel, may I ask for your help to place the notebook in the correct path?
Here is what I tried:
```
image: "python:latest"
pages:
  stage: deploy
  before_script:
    - python -m pip install jupyterlite
    - mkdir -p gitlab-demo/content/
    - cp hello.ipynb gitlab-demo/content/


  script:
    - cd gitlab-demo && jupyter lite build --contents content --output-dir public && mv public ..


    
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - main # the branch you want to publish
```
Here is the [log](https://gitlab.gwdg.de/crc1456/livedocs/jupyter-lite-compare_view-demo/-/jobs/965123
), and here is a text difference between your advanced example and my minimal example:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/44469195/189934098-4543e159-37a7-4702-9d51-a9117fea3be2.png">

**Comment by kolibril13** [comment]
Now I've figured it out and wrote a minimal example for using JupyterLite in GitLab.
https://gitlab.gwdg.de/crc1456/livedocs/jupyterlite-minimal-example
https://crc1456.pages.gwdg.de/livedocs/jupyterlite-minimal-example/lab/index.html

I think this might be a nice addition to the hint at:
https://jupyterlite.readthedocs.io/en/latest/howto/deployment/gitlab.html#deploying-on-gitlab-pages

For example:

"When you're looking for a JupyterLite GitLab template, there is a [minimal example](https://gitlab.gwdg.de/crc1456/livedocs/jupyterlite-minimal-example) and a [more involved example](https://gitlab.com/benabel/jupyterlite-template)."

**Comment by kolibril13** [comment]
One more question regarding the minimal example configuration:
I want to disable the jupyter tour with this snippet (from https://github.com/jupyterlab-contrib/jupyterlab-tour#disabling-tours-with-pageconfigjson) :
```
{
  "disabledExtensions": {
    "jupyterlab-tour:user-tours": true,
    "jupyterlab-tour:default-tours": true,
  }
}
```
My current [jupyter-lite.json](https://gitlab.gwdg.de/crc1456/livedocs/jupyterlite-minimal-example/-/blob/main/gitlab-demo/repl/jupyter-lite.json) file looks like this, and it does not disable the tour: 
```
{
  "jupyter-lite-schema-version": 0,
  "jupyter-config-data": {
    "disabledExtensions": [
      "@jupyterlab/drawio-extension",
      "jupyterlab-kernel-spy",
      "jupyterlab-tour"
    ]
  }
}
```
How can that be done?

**Comment by jtpio** [comment]
> I think this might be a nice addition to the hint at:

Sure, would you like to submit a PR? Thanks!

> My current [jupyter-lite.json](https://gitlab.gwdg.de/crc1456/livedocs/jupyterlite-minimal-example/-/blob/main/gitlab-demo/repl/jupyter-lite.json) file looks like this, and it does not disable the tour:

This file seems to be placed under `/repl/jupyter-lite.json` at the moment. Maybe try to move it to the parent folder?

**Comment by kolibril13** [comment]
I will do that :)

Thanks for the hint! Moving it to the parent folder solved the problem.
